name: Auto-Commit Changes

on:
  schedule:
    - cron: '*/10 * * * *' # This will run every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes and commit
      run: |
        FILE_TO_COMMIT="sortByValue.ts"
        
        # Check if the file exists and make a change (or create it if it doesn't exist)
        if [ -f "$FILE_TO_COMMIT" ]; then
          echo "Updating $FILE_TO_COMMIT"
          echo "console.log('Auto-update for $FILE_TO_COMMIT');" >> $FILE_TO_COMMIT
        else
          echo "Creating $FILE_TO_COMMIT"
          echo "console.log('Auto-update for $FILE_TO_COMMIT');" > $FILE_TO_COMMIT
        fi
        
        git config --global user.name 'aelishRollo'
        git config --global user.email 'alecrollison@icloud.com'
        git add $FILE_TO_COMMIT
        git commit -m "Auto-update $FILE_TO_COMMIT"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
